export default function filterRoles(allRoles, currentUserRoles) {
  let filteredRoles;
  if (currentUserRoles.includes('admin') || currentUserRoles.includes('root admin')) {
    filteredRoles = Array.from(allRoles)
  } else {
    /*
      Student: Value of role.name that generated by Canvas will be 'StudentEnrollment'.
      Designer: Value of role.name that generated by Canvas will be 'DesignerEnrollment'.
    */
    filteredRoles = Array.from(allRoles).filter(role => {
      return !['StudentEnrollment', 'DesignerEnrollment'].includes(role.name)
    })
  }

  return filteredRoles
}
