image: docker:19.03.7
stages:
  - build
  - test
  - push
  - deploy
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CANVAS_LMS_DEPLOY_PORT: $TESTING_DEPLOY_PORT
  CANVAS_LMS_DEPLOY_HOST: $TESTING_DEPLOY_HOST
  CANVAS_LMS_DOCKER_LOG_MAX_SIZE: $TESTING_DOCKER_LOG_MAX_SIZE
  CANVAS_LMS_CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  CANVAS_LMS_CONTAINER_NAME: $TESTING_CONTAINER_NAME
  CANVAS_LMS_NUMBER_OF_WORKERS: $TESTING_NUMBER_OF_WORKERS
  CANVAS_LMS_CACHE_STORE_CACHE_STORE: $TESTING_CACHE_STORE_CACHE_STORE
  CANVAS_LMS_CASSANDRA_SERVERS: $TESTING_CASSANDRA_SERVERS
  CANVAS_LMS_CASSANDRA_PAGE_VIEWS_KEYSPACE: $TESTING_CASSANDRA_PAGE_VIEWS_KEYSPACE
  CANVAS_LMS_CASSANDRA_AUDITORS_KEYSPACE: $TESTING_CASSANDRA_AUDITORS_KEYSPACE
  CANVAS_LMS_DATABASE_DATABASE: $TESTING_DATABASE_DATABASE
  CANVAS_LMS_DATABASE_USERNAME: $TESTING_DATABASE_USERNAME
  CANVAS_LMS_DATABASE_PASSWORD: $TESTING_DATABASE_PASSWORD
  DATABASE_HOST: $TESTING_DATABASE_HOST
  CANVAS_LMS_DOMAIN_DOMAIN: $TESTING_DOMAIN_DOMAIN
  CANVAS_LMS_DOMAIN_SSL: $TESTING_DOMAIN_SSL
  CANVAS_LMS_DYNAMIC_SETTINGS_ENCRYPTION_SECRET: $TESTING_DYNAMIC_SETTINGS_ENCRYPTION_SECRET
  CANVAS_LMS_DYNAMIC_SETTINGS_SIGNING_SECRET: $TESTING_DYNAMIC_SETTINGS_SIGNING_SECRET
  CANVAS_LMS_DYNAMIC_SETTINGS_MATH_MAN_BASE_URL: $TESTING_DYNAMIC_SETTINGS_MATH_MAN_BASE_URL
  CANVAS_LMS_DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_SVG: $TESTING_DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_SVG
  CANVAS_LMS_DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_MML: $TESTING_DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_MML
  CANVAS_LMS_DYNAMIC_SETTINGS_RICH_CONTENT_SERVICE_HOST: $TESTING_DYNAMIC_SETTINGS_RICH_CONTENT_SERVICE_HOST
  CANVAS_LMS_DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_BASE_URL: $TESTING_DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_BASE_URL
  CANVAS_LMS_DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_URL: $TESTING_DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_URL
  CANVAS_LMS_FILE_STORAGE_STORAGE: $TESTING_FILE_STORAGE_STORAGE
  CANVAS_LMS_FILE_STORAGE_PATH_PREFIX: $TESTING_FILE_STORAGE_PATH_PREFIX
  CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_ADDRESS: $TESTING_OUTGOING_MAIL_PRODUCTION_ADDRESS
  CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_PORT: $TESTING_OUTGOING_MAIL_PRODUCTION_PORT
  CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_DOMAIN: $TESTING_OUTGOING_MAIL_PRODUCTION_DOMAIN
  CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_OUTGOING_ADDRESS: $TESTING_OUTGOING_MAIL_PRODUCTION_OUTGOING_ADDRESS
  CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_DEFAULT_NAME: $TESTING_OUTGOING_MAIL_PRODUCTION_DEFAULT_NAME
  CANVAS_LMS_PREDOC_URL: $TESTING_PREDOC_URL
  CANVAS_LMS_REDIS_SERVERS: $TESTING_REDIS_SERVERS
  CANVAS_LMS_REDIS_DATABASE: $TESTING_REDIS_DATABASE
  CANVAS_LMS_SAML_ENTITY_ID: $TESTING_SAML_ENTITY_ID
  CANVAS_LMS_SAML_TECH_CONTACT_NAME: $TESTING_SAML_TECH_CONTACT_NAME
  CANVAS_LMS_SAML_TECH_CONTACT_EMAIL: $TESTING_SAML_TECH_CONTACT_EMAIL
  CANVAS_LMS_SAML_PRIVATE_KEY: $TESTING_SAML_PRIVATE_KEY
  CANVAS_LMS_SAML_CERTIFICATE: $TESTING_SAML_CERTIFICATE
  CANVAS_LMS_SECURITY_ENCRYPTION_KEY: $TESTING_SECURITY_ENCRYPTION_KEY
  CANVAS_LMS_SECURITY_LTI_ISS: $TESTING_SECURITY_LTI_ISS
  CANVAS_LMS_EXTERNAL_TMP_DIRECTORY: $TESTING_EXTERNAL_TMP_DIRECTORY
  CANVAS_LMS_EXTERNAL_LOG_DIRECTORY: $TESTING_EXTERNAL_LOG_DIRECTORY
  CANVAS_LMS_EXTERNAL_SAML_DIRECTORY: $TESTING_EXTERNAL_SAML_DIRECTORY
  CANVAS_LMS_PASSENGERFILE_MAX_POOL_SIZE: $TESTING_PASSENGERFILE_MAX_POOL_SIZE
  CANVAS_LMS_PASSENGERFILE_MAX_REQUEST_QUEUE_SIZE: $TESTING_PASSENGERFILE_MAX_REQUEST_QUEUE_SIZE
  CANVAS_LMS_PASSENGERFILE_MAX_REQUESTS: $TESTING_PASSENGERFILE_MAX_REQUESTS
  CANVAS_LMS_PASSENGERFILE_POOL_IDLE_TIME: $TESTING_PASSENGERFILE_POOL_IDLE_TIME

.fetch-image-tag: &fetch-image-tag
  - if expr match $CI_COMMIT_BRANCH '^releases/.*$';
    then IMAGE_TAG="$( echo $CI_COMMIT_BRANCH | cut -d '/' -f 2 )";
    else IMAGE_TAG=latest;
    fi;

build:
  stage: build
  before_script:
    - chmod +x config.sh
    - apk update && apk add bash
    - ./config.sh
  script:
    - *fetch-image-tag
    - docker build --file Dockerfile.cool     -t $CI_REGISTRY_IMAGE:$IMAGE_TAG          .
    - docker build --file Dockerfile.deployer -t $CI_REGISTRY_IMAGE/deployer:$IMAGE_TAG .
  only:
    - /^releases/.*$/@ntu-cool/canvas-lms
    - merge_requests
    - dlc-master
    - dev

test:
  stage: test
  script:
    - echo Please update test cases
  # coverage: '/Code coverage: \d+\.\d+/'
  only:
    - /^releases/.*$/@ntu-cool/canvas-lms
    - merge_requests
    - dlc-master
    - dev

push-image:
  stage: push
  script:
    - *fetch-image-tag
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/deployer:$IMAGE_TAG
  needs:
    - job: build
      artifacts: true
  when: manual
  only:
    - /^releases/.*$/@ntu-cool/canvas-lms

include: 
  - project: 'ntu-cool/cool-deploy-hub'
    ref: master
    file: '.gitlab-ci-ssh.yml'
  - local: .gitlab-ci-deploy.yml 

deploy-testing:
  stage: deploy
  extends: 
    - .ssh
    - .canvas-lms-deploy
  when: manual
  only:
    - /^releases/.*$/@ntu-cool/canvas-lms
    - tags
