.check-image-tag: &check-image-tag
  - if expr match $CI_COMMIT_BRANCH '^releases/.*$';
    then CANVAS_LMS_IMAGE_TAG="$( echo $CI_COMMIT_BRANCH | cut -d '/' -f 2 )";
    elif [ ! -z "$CI_COMMIT_TAG" ];
    then CANVAS_LMS_IMAGE_TAG=$CI_COMMIT_TAG;
    fi;

.pre-deploy: &pre-deploy
  - ssh $DEPLOY_USER@$CANVAS_LMS_DEPLOY_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - ssh $DEPLOY_USER@$CANVAS_LMS_DEPLOY_HOST "docker pull $CANVAS_LMS_CI_REGISTRY_IMAGE:$CANVAS_LMS_IMAGE_TAG"
  - ssh $DEPLOY_USER@$CANVAS_LMS_DEPLOY_HOST "docker pull $CANVAS_LMS_CI_REGISTRY_IMAGE/deployer:$CANVAS_LMS_IMAGE_TAG"

.deploy-container: &deploy-container
    - ssh $DEPLOY_USER@$CANVAS_LMS_DEPLOY_HOST "docker run
      --rm
      --env CANVAS_LMS_CI_REGISTRY_IMAGE=$CANVAS_LMS_CI_REGISTRY_IMAGE
      --env CANVAS_LMS_IMAGE_TAG=$CANVAS_LMS_IMAGE_TAG
      --env CANVAS_LMS_DEPLOY_HOST=$CANVAS_LMS_DEPLOY_HOST
      --env CANVAS_LMS_DEPLOY_PORT=$CANVAS_LMS_DEPLOY_PORT
      --env CANVAS_LMS_EXTERNAL_TMP_DIRECTORY=$CANVAS_LMS_EXTERNAL_TMP_DIRECTORY
      --env CANVAS_LMS_EXTERNAL_LOG_DIRECTORY=$CANVAS_LMS_EXTERNAL_LOG_DIRECTORY
      --env CANVAS_LMS_EXTERNAL_SAML_DIRECTORY=$CANVAS_LMS_EXTERNAL_SAML_DIRECTORY
      --env CANVAS_LMS_EXTERNAL_CSS_DIRECTORY=$CANVAS_LMS_EXTERNAL_CSS_DIRECTORY
      --env CANVAS_LMS_DOCKER_LOG_MAX_SIZE=$CANVAS_LMS_DOCKER_LOG_MAX_SIZE
      --env DEPLOY_PORT=$CANVAS_LMS_DEPLOY_PORT
      --env CACHE_STORE_CACHE_STORE=$CANVAS_LMS_CACHE_STORE_CACHE_STORE
      --env CASSANDRA_SERVERS=$CANVAS_LMS_CASSANDRA_SERVERS
      --env CASSANDRA_PAGE_VIEWS_KEYSPACE=$CANVAS_LMS_CASSANDRA_PAGE_VIEWS_KEYSPACE
      --env CASSANDRA_AUDITORS_KEYSPACE=$CANVAS_LMS_CASSANDRA_AUDITORS_KEYSPACE
      --env DATABASE_DATABASE=$CANVAS_LMS_DATABASE_DATABASE
      --env DATABASE_USERNAME=$CANVAS_LMS_DATABASE_USERNAME
      --env DATABASE_PASSWORD=$CANVAS_LMS_DATABASE_PASSWORD
      --env DATABASE_HOST=$DATABASE_HOST
      --env DOMAIN_DOMAIN=$CANVAS_LMS_DOMAIN_DOMAIN
      --env DOMAIN_SSL=$CANVAS_LMS_DOMAIN_SSL
      --env DYNAMIC_SETTINGS_ENCRYPTION_SECRET=$CANVAS_LMS_DYNAMIC_SETTINGS_ENCRYPTION_SECRET
      --env DYNAMIC_SETTINGS_SIGNING_SECRET=$CANVAS_LMS_DYNAMIC_SETTINGS_SIGNING_SECRET
      --env DYNAMIC_SETTINGS_MATH_MAN_BASE_URL=$CANVAS_LMS_DYNAMIC_SETTINGS_MATH_MAN_BASE_URL
      --env DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_SVG=$CANVAS_LMS_DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_SVG
      --env DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_MML=$CANVAS_LMS_DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_MML
      --env DYNAMIC_SETTINGS_RICH_CONTENT_SERVICE_HOST=$CANVAS_LMS_DYNAMIC_SETTINGS_RICH_CONTENT_SERVICE_HOST
      --env DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_BASE_URL=$CANVAS_LMS_DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_BASE_URL
      --env DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_URL=$CANVAS_LMS_DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_URL
      --env FILE_STORE_STORAGE=$CANVAS_LMS_FILE_STORE_STORAGE
      --env FILE_STORE_PATH_PREFIX=$CANVAS_LMS_FILE_STORE_PATH_PREFIX
      --env OUTGOING_MAIL_PRODUCTION_ADDRESS=$CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_ADDRESS
      --env OUTGOING_MAIL_PRODUCTION_PORT=$CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_PORT
      --env OUTGOING_MAIL_PRODUCTION_DOMAIN=$CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_DOMAIN
      --env OUTGOING_MAIL_PRODUCTION_OUTGOING_ADDRESS=$CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_OUTGOING_ADDRESS
      --env OUTGOING_MAIL_PRODUCTION_DEFAULT_NAME=$CANVAS_LMS_OUTGOING_MAIL_PRODUCTION_DEFAULT_NAME
      --env PREDOC_URL=$CANVAS_LMS_PREDOC_URL
      --env REDIS_SERVERS=$CANVAS_LMS_REDIS_SERVERS
      --env REDIS_DATABASE=$CANVAS_LMS_REDIS_DATABASE
      --env SAML_ENTITY_ID=$CANVAS_LMS_SAML_ENTITY_ID
      --env SAML_TECH_CONTACT_NAME=$CANVAS_LMS_SAML_TECH_CONTACT_NAME
      --env SAML_TECH_CONTACT_EMAIL=$CANVAS_LMS_SAML_TECH_CONTACT_EMAIL
      --env SAML_PRIVATE_KEY=$CANVAS_LMS_SAML_PRIVATE_KEY
      --env SAML_CERTIFICATE=$CANVAS_LMS_SAML_CERTIFICATE
      --env SECURITY_ENCRYPTION_KEY=$CANVAS_LMS_SECURITY_ENCRYPTION_KEY
      --env SECURITY_LTI_ISS=$CANVAS_LMS_SECURITY_LTI_ISS
      --env PASSENGERFILE_MAX_POOL_SIZE=$CANVAS_LMS_PASSENGERFILE_MAX_POOL_SIZE
      --env PASSENGERFILE_MAX_REQUEST_QUEUE_SIZE=$CANVAS_LMS_PASSENGERFILE_MAX_REQUEST_QUEUE_SIZE
      --env PASSENGERFILE_MAX_REQUESTS=$CANVAS_LMS_PASSENGERFILE_MAX_REQUESTS
      --env PASSENGERFILE_POOL_IDLE_TIME=$CANVAS_LMS_PASSENGERFILE_POOL_IDLE_TIME
      --volume /var/run/docker.sock:/var/run/docker.sock
      $CANVAS_LMS_CI_REGISTRY_IMAGE/deployer:$CANVAS_LMS_IMAGE_TAG
        --project-name $CANVAS_LMS_CONTAINER_NAME
        up --detach --scale application=$CANVAS_LMS_NUMBER_OF_WORKERS"

.migration: &migration
  - ssh $DEPLOY_USER@$CANVAS_LMS_DEPLOY_HOST "docker exec -t --env RAILS_ENV=production canvas-lms_web_1 bundle exec rake db:migrate:predeploy"
  - ssh $DEPLOY_USER@$CANVAS_LMS_DEPLOY_HOST "docker exec -t --env RAILS_ENV=production canvas-lms_web_1 bundle exec rake db:load_notifications"

.canvas-lms-deploy:
  script:
    - *check-image-tag
    - *pre-deploy
    - *deploy-container
    - *migration
