inherit_from: .rubocop.common.yml

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Naming/VariableNumber:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false # we never bothered creating an ApplicationRecord
Rails/HasManyOrHasOneDependent:
  # It whines about update_all too much, which we use a lot specifically to
  # bypass validations and any other AR-ness
  Enabled: false
Rails/ReadWriteAttribute:
  Enabled: false # accessors are often defined in terms of read_attribute
Rails/SkipsModelValidations:
  Enabled: false
Rails/TimeZone:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/ExpectChange:
  Enabled: false
RSpec/HookArgument:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/ScatteredSetup:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
    - spec/shared_examples/**/*.rb
Style/ClassAndModuleChildren:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/Dir:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueModifier:
  Severity: warning
Style/RescueStandardError:
  EnforcedStyle: implicit
  Enabled: false
Style/ReturnNil:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
