# it is intended that this be used exclusive of all other docker-compose.*yml files in CI
version: "2.3"
services:
  canvas:
    image: $PATCHSET_TAG
    links:
      - postgres
      - redis
      - cassandra
      - dynamodb
    environment:
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160
      RAILS_ENV: test
      RANDOMIZE_SEQUENCES: 1
      DISABLE_SPRING: 'true'
      RERUNS_RETRY:
      MAX_FAIL:
      COVERAGE:
      FORCE_FAILURE:

      # parallel_tests
      CI_NODE_TOTAL:
      CI_NODE_INDEX:
      DOCKER_PROCESSES:
      EXCLUDE_TESTS:
      TEST_PATTERN:
    # this will stop passenger from booting so the container isn't running anything at all once up
    command: sleep infinity
    init: true

  redis:
    image: starlord.inscloudgate.net/jenkins/redis:alpine
    init: true

  postgres:
    image: starlord.inscloudgate.net/jenkins/postgis:$POSTGRES-${POSTGIS:-2.5}
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

      # parallel_tests
      DOCKER_PROCESSES:
    init: true

  cassandra:
    image: starlord.inscloudgate.net/jenkins/cassandra:2.2
    environment:
      CASSANDRA_START_RPC: 'true'
    init: true

  dynamodb:
    image: starlord.inscloudgate.net/jenkins/dynamodb-local
    command: -jar DynamoDBLocal.jar #-dbPath /home/dynamodblocal
    init: true
