version: '2'

x-default:
  &default-setting
  image: ${CANVAS_LMS_CI_REGISTRY_IMAGE}:${CANVAS_LMS_IMAGE_TAG}
  group_add:
    - canvasuser
  user: canvasuser
  links:
    - redis
  logging:
    driver: json-file
    options:
      max-size: "${CANVAS_LMS_DOCKER_LOG_MAX_SIZE}"
  environment:
    - CACHE_STORE_CACHE_STORE
    - CASSANDRA_SERVERS
    - CASSANDRA_PAGE_VIEWS_KEYSPACE
    - CASSANDRA_AUDITORS_KEYSPACE
    - DATABASE_DATABASE
    - DATABASE_USERNAME
    - DATABASE_PASSWORD
    - DATABASE_HOST
    - DOMAIN_DOMAIN
    - DOMAIN_SSL
    - DYNAMIC_SETTINGS_ENCRYPTION_SECRET
    - DYNAMIC_SETTINGS_SIGNING_SECRET
    - DYNAMIC_SETTINGS_MATH_MAN_BASE_URL
    - DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_SVG
    - DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_MML
    - DYNAMIC_SETTINGS_RICH_CONTENT_SERVICE_HOST
    - DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_BASE_URL
    - DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_URL
    - FILE_STORE_STORAGE
    - FILE_STORE_PATH_PREFIX
    - OUTGOING_MAIL_PRODUCTION_ADDRESS
    - OUTGOING_MAIL_PRODUCTION_PORT
    - OUTGOING_MAIL_PRODUCTION_DOMAIN
    - OUTGOING_MAIL_PRODUCTION_OUTGOING_ADDRESS
    - OUTGOING_MAIL_PRODUCTION_DEFAULT_NAME
    - PREDOC_URL
    - REDIS_SERVERS
    - REDIS_DATABASE
    - SAML_ENTITY_ID
    - SAML_TECH_CONTACT_NAME
    - SAML_TECH_CONTACT_EMAIL
    - SAML_PRIVATE_KEY
    - SAML_CERTIFICATE
    - SECURITY_ENCRYPTION_KEY
    - SECURITY_LTI_ISS
    - PASSENGERFILE_MAX_POOL_SIZE
    - PASSENGERFILE_MAX_REQUEST_QUEUE_SIZE
    - PASSENGERFILE_MAX_REQUESTS
    - PASSENGERFILE_POOL_IDLE_TIME
  volumes:
    - ${CANVAS_LMS_EXTERNAL_TMP_DIRECTORY}:/var/canvas/tmp
    - ${CANVAS_LMS_EXTERNAL_LOG_DIRECTORY}:/var/canvas/log
    - ${CANVAS_LMS_EXTERNAL_SAML_DIRECTORY}:/var/canvas/config/saml
    - ${CANVAS_LMS_EXTERNAL_CSS_DIRECTORY}:/var/canvas/public/dist/brandable_css
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  restart: always

services:
  web:
    << : *default-setting
    ports:
      - "${CANVAS_LMS_DEPLOY_HOST}:${CANVAS_LMS_DEPLOY_PORT}:3000"

  jobs:
    << : *default-setting
    command: bundle exec script/delayed_job run

  redis:
    image: redis:6.2-rc-alpine
