# it is intended that this be used exclusive of all other docker-compose.*yml files in CI
version: "2.3"
services:
  web:
    image: $PATCHSET_TAG
    links:
      - postgres
      - redis
      - cassandra
      - dynamodb
    environment:
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:sekret@postgres:5432/canvas_test0
      RANDOMIZE_SEQUENCES: 1
      DISABLE_SPRING: 'true'
      RERUNS_RETRY:
      MAX_FAIL:
      COVERAGE:
      FORCE_FAILURE:

      # parallel_tests
      CI_NODE_TOTAL:
      CI_NODE_INDEX:
      DOCKER_PROCESSES:
      EXCLUDE_TESTS:
      TEST_PATTERN:
    # this will stop passenger from booting so the container isn't running anything at all once up
    command: /tini -- sleep infinity

  redis:
    image: starlord.inscloudgate.net/jenkins/redis:alpine

  postgres:
    build:
      context: build/docker-compose/postgres/
    environment:
      POSTGRES_PASSWORD: sekret

      # parallel_tests
      DOCKER_PROCESSES:

  cassandra:
    build:
      context: build/docker-compose/cassandra/
    environment:
      CASSANDRA_START_RPC: 'true'

  dynamodb:
    build:
      context: build/docker-compose/dynamodb/
    command: -jar DynamoDBLocal.jar #-dbPath /home/dynamodblocal
