# it is intended that this be used exclusive of all other docker-compose.*yml files in CI
version: "2.3"
services:
  web:
    # use master if NAME is unavailable
    image: "${PATCHSET_TAG}"
    links:
      - postgres
      - redis
      - cassandra
    environment:
      ENCRYPTION_KEY: facdd3a131ddd8988b14f6e4e01039c93cfa0160
      RAILS_ENV: test
      RAILS_DB_NAME_TEST: 'canvas_test'
      RAILS_DB_HOST: postgres
      RAILS_DB_PASSWORD: ''
      DATABASE_URL: "postgres://postgres@postgres:5432/canvas_test"
      RANDOMIZE_SEQUENCES: 1
      CI_NODE_TOTAL: $CI_NODE_TOTAL
      CI_NODE_INDEX: $CI_NODE_INDEX
      KNAPSACK_ENABLED: $KNAPSACK_ENABLED
      KNAPSACK_TEST_FILE_PATTERN: $KNAPSACK_TEST_FILE_PATTERN
      KNAPSACK_EXCLUDE_REGEX: $KNAPSACK_EXCLUDE_REGEX
      KNAPSACK_TEST_DIR: $KNAPSACK_TEST_DIR
      KNAPSACK_GENERATE_REPORT: $KNAPSACK_GENERATE_REPORT

  redis:
    image: redis:alpine

  postgres:
    build: ./build/docker-compose/postgres/9.5

  cassandra:
    build: ./build/docker-compose/cassandra
    environment:
      CASSANDRA_START_RPC: 'true'
