FROM docker:19.03.15

WORKDIR /usr/workspace

RUN apk add --no-cache \
        py3-pip python3-dev libffi-dev openssl-dev curl gcc libc-dev make rust cargo \
    && pip3 install docker-compose

COPY docker-compose.deploy.yml docker-compose.yml

ENTRYPOINT ["docker-compose"]
