version: '2'
services:
  web:
    image: ${CANVAS_LMS_CI_REGISTRY_IMAGE}:${CANVAS_LMS_IMAGE_TAG}
    ports:
      - "${CANVAS_LMS_DEPLOY_PORT}:3000"
    links:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "${CANVAS_LMS_DOCKER_LOG_MAX_SIZE}"
    environment:
      - CACHE_STORE_CACHE_STORE
      - CASSANDRA_SERVERS
      - CASSANDRA_PAGE_VIEWS_KEYSPACE
      - CASSANDRA_AUDITORS_KEYSPACE
      - DATABASE_DATABASE
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DOMAIN_DOMAIN
      - DYNAMIC_SETTINGS_ENCRYPTION_SECRET
      - DYNAMIC_SETTINGS_SIGNING_SECRET
      - DYNAMIC_SETTINGS_MATH_MAN_BASE_URL
      - DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_SVG
      - DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_MML
      - DYNAMIC_SETTINGS_RICH_CONTENT_SERVICE_HOST
      - DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_BASE_URL
      - DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_URL
      - FILE_STORAGE_STORAGE
      - FILE_STORAGE_PATH_PREFIX
      - OUTGOING_MAIL_PRODUCTION_ADDRESS
      - OUTGOING_MAIL_PRODUCTION_PORT
      - OUTGOING_MAIL_PRODUCTION_DOMAIN
      - OUTGOING_MAIL_PRODUCTION_OUTGOING_ADDRESS
      - OUTGOING_MAIL_PRODUCTION_DEFAULT_NAME
      - PREDOC_URL
      - REDIS_SERVERS
      - REDIS_DATABASE
      - SAML_ENTITY_ID
      - SAML_TECH_CONTACT_NAME
      - SAML_TECH_CONTACT_EMAIL
      - SAML_PRIVATE_KEY
      - SAML_CERTIFICATE
      - SECURITY_ENCRYPTION_KEY
      - SECURITY_LTI_ISS
    volumes:
      - ${CANVAS_LMS_EXTERNAL_TMP_DIR}:/usr/workspace/tmp
      - ${CANVAS_LMS_EXTERNAL_LOG_DIR}:/usr/workspace/log
      - ${CANVAS_LMS_EXTERNAL_SAML_DIR}:/usr/workspace/config/saml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  jobs:
    image: ${CANVAS_LMS_CI_REGISTRY_IMAGE}:${CANVAS_LMS_IMAGE_TAG}
    links:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "${CANVAS_LMS_DOCKER_LOG_MAX_SIZE}"
    environment:
      - CACHE_STORE_CACHE_STORE
      - CASSANDRA_SERVERS
      - CASSANDRA_PAGE_VIEWS_KEYSPACE
      - CASSANDRA_AUDITORS_KEYSPACE
      - DATABASE_DATABASE
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_PORT
      - DOMAIN_DOMAIN
      - DYNAMIC_SETTINGS_ENCRYPTION_SECRET
      - DYNAMIC_SETTINGS_SIGNING_SECRET
      - DYNAMIC_SETTINGS_MATH_MAN_BASE_URL
      - DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_SVG
      - DYNAMIC_SETTINGS_MATH_MAN_USE_FOR_MML
      - DYNAMIC_SETTINGS_RICH_CONTENT_SERVICE_HOST
      - DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_BASE_URL
      - DYNAMIC_SETTINGS_COMMON_CARTRIDGE_VIEWER_URL
      - FILE_STORAGE_STORAGE
      - FILE_STORAGE_PATH_PREFIX
      - OUTGOING_MAIL_PRODUCTION_ADDRESS
      - OUTGOING_MAIL_PRODUCTION_PORT
      - OUTGOING_MAIL_PRODUCTION_DOMAIN
      - OUTGOING_MAIL_PRODUCTION_OUTGOING_ADDRESS
      - OUTGOING_MAIL_PRODUCTION_DEFAULT_NAME
      - PREDOC_URL
      - REDIS_SERVERS
      - REDIS_DATABASE
      - SAML_ENTITY_ID
      - SAML_TECH_CONTACT_NAME
      - SAML_TECH_CONTACT_EMAIL
      - SAML_PRIVATE_KEY
      - SAML_CERTIFICATE
      - SECURITY_ENCRYPTION_KEY
      - SECURITY_LTI_ISS
    volumes:
      - ${CANVAS_LMS_EXTERNAL_TMP_DIR}:/usr/workspace/tmp
      - ${CANVAS_LMS_EXTERNAL_LOG_DIR}:/usr/workspace/log
      - ${CANVAS_LMS_EXTERNAL_SAML_DIR}:/usr/workspace/config/saml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    command: bundle exec script/delayed_job run

  redis:
    image: redis:alpine
