# to use this for global lookups add docker-compose/dynamodb.override.yml
# to your COMPOSE_FILE var in .env
# Then:
# - Run `GlobalLookups.initialize_ddb_for_development!` from a console
version: '2.3'
services:
  web:
    depends_on:
      - "dynamodb"
    links:
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'

  dynamodb:
    image: instructure/dynamo-local-admin:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"