# to use this add docker-compose/js-tests.override.yml
# to your COMPOSE_FILE var in .env

version: '2.3'
services:
  js-tests:
    build:
      context: .
      dockerfile: docker-compose/karma/Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: CI
    cap_add:
      - SYS_ADMIN
    # for linux the default profile restricts mount usage, set to have no restrictions
    security_opt:
      - apparmor:unconfined
    entrypoint: /root/entrypoint.sh
    command: yarn run test:karma:watch:headless
