/*
 * Copyright (C) 2021 - present Instructure, Inc.
 *
 * This file is part of Canvas.
 *
 * Canvas is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3 of the License.
 *
 * Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

// This file is created by the NTU COOL Team
export default function filterRoles(allRoles, currentUserRoles) {
  let filteredRoles
  if (currentUserRoles.includes('admin') || currentUserRoles.includes('root admin')) {
    filteredRoles = Array.from(allRoles)
  } else {
    /*
      Student: Value of role.name that generated by Canvas will be 'StudentEnrollment'.
      Designer: Value of role.name that generated by Canvas will be 'DesignerEnrollment'.
    */
    filteredRoles = Array.from(allRoles).filter(role => {
      return !['StudentEnrollment', 'DesignerEnrollment'].includes(role.name)
    })
  }

  return filteredRoles
}
