---
immersive_reader_wiki_pages:
  state: hidden
  display_name: Immersive Reader (Wiki Pages)
  description: |-
    Makes an Immersive Reader link option show up on wiki pages.
  applies_to: RootAccount
  root_opt_in: true
