---
developer_key_support_includes:
  state: hidden
  display_name: Developer Key Include Parameter Support
  description: |-
    Provides a flag on the Devloper Key to support Include Parameters on API requests
  applies_to: SiteAdmin
site_admin_keys_only:
  state: hidden
  display_name: Only show site admin keys in the site admin UI
  description: |-
    If enabled, the site admin developer key UI will only show
    site admin developer keys. Note that this only affects
    Canvas instances where root accounts are on the same shard
    as the site admin account. Behavior in other instances
    already behaved in this way.
  applies_to: SiteAdmin
disable_graphql_authentication:
  state: hidden
  display_name: Disable authentication for GraphQL
  description: |-
    If enabled, GraphQL queries will not require
    users to be signed in or use an access token.
  applies_to: SiteAdmin
microsoft_group_enrollments_syncing:
  state: hidden
  display_name: Microsoft Group enrollment syncing
  description: |-
    If enabled, syncing course enrollments to Microsoft Groups will be
    available. Account admins may enable this in account settings.
  applies_to: RootAccount
lti_platform_storage:
  state: hidden
  display_name: LTI Platform Storage
  description: |-
    If enabled, allows new window.postMessage subjects for the LTI Platform
    Storage spec, and sends reponse messages to all postMessage.
  applies_to: SiteAdmin
lti_multiple_assignment_deep_linking:
  state: hidden
  display_name: LTI Multiple Assignment Deep Linking
  description: |-
    If enabled, allows multiple deep link support for assignments and modules.
  applies_to: RootAccount
lti_deep_linking_module_index_menu_modal:
  state: hidden
  display_name: LTI Deep Linking for Module Index Menu
  description: |-
    If enabled, allows deep linking from the module index via a modal.
  applies_to: RootAccount
lti_deep_linking_line_items:
  state: hidden
  display_name: LTI Deep Linking Line Items
  description: |-
    If enabled, creates assignments from LineItems in deep link messages.
  applies_to: RootAccount
lti_assignment_page_line_items:
  state: hidden
  display_name: LTI Deep Linking Line Items on Assignment edit page
  description: |-
    If enabled, creates assignments from LineItems in deep link messages on the assignment edit page.
  applies_to: RootAccount
api_auth_error_updates:
  state: hidden
  display_name: Updates to JSON API auth error HTTP code and JSON status field
  description: |-
    If enabled, an "unauthorized" response from the JSON API will return a 403
    (Forbidden) instead of a 401 code, to be more in line with HTTP standards.
    Also, when the API returns a unauthenticated or unauthorized JSON error,
    the "status" field will not be localized; it will always be given in
    English.
  applies_to: SiteAdmin
no_redirect_on_oauth_token_method:
  state: hidden
  display_name: Updates to OAuth 2.0 flow to stop redirecting in the 'token' authentication
  description: |-
    If enabled, the OAuth 2.0 will now correctly return 4xx status codes to the
    requesting client instead of redirecting them to themselves
  applies_to: SiteAdmin
  environments:
    development:
      state: on
    ci:
      state: on
variable_substitution_numeric_to_string:
  state: hidden
  display_name: Returns string values instead of numeric values in variable substitutions
  description: |-
    If enabled, variable substitutions will return string values instead of numeric values
  applies_to: RootAccount
ags_scores_multiple_files:
  state: hidden
  display_name: Allow multiple file AGS submissions to count as only one submission
  description: |-
    This feature makes it so that when multiple files are submitted together by
    a third party tool via the Assignments and Grade Service API they will be
    grouped as one submission, rather than creating multiple separate submissions.
  applies_to: RootAccount
  environments:
    development:
      state: on
lti_tools_from_federated_parents:
  state: hidden
  display_name: Show LTI tools from federated parent accounts
  description: |-
    If enabled, LTI tools installed in federated parent accounts will be
    available / visible in child accounts.
  applies_to: SiteAdmin
