---
buttons_and_icons_root_account:
  state: allowed
  applies_to: RootAccount
  display_name: RCE Icon Maker
  description: |-
    Manage a library of custom icons from the RCE.
  environments:
    production:
      state: hidden

buttons_and_icons_cropper:
  state: hidden
  display_name: Cropper & Associated Features in Buttons & Icons
  description: |-
    When enabled, turns on the Button & Icons image cropper, course images
    source, and upload image source.
  applies_to: SiteAdmin

rce_ux_improvements:
  state: hidden
  display_name: RCE UX Improvements
  description: Improve and streamline the RCE button and tray UX
  applies_to: SiteAdmin

rce_better_paste:
  state: hidden
  display_name: Enhanced RCE paste from clipboard
  description: Handle pasting of files, especially images.
  applies_to: SiteAdmin
  environments:
    development:
      state: allowed_on
    beta:
      state: allowed_on
    ci:
      state: allowed_on

rce_new_external_tool_dialog_in_canvas:
  state: hidden
  display_name: RCE Use New External Tool Dialog in Canvas
  description: Use the new external tool dialog when the RCE is running in Canvas. The new dialog is always used in new quizzes.
  applies_to: SiteAdmin
  environments:
    development:
      state: allowed_on
    beta:
      state: allowed_on
    ci:
      state: allowed_on

explicit_latex_typesetting:
  state: hidden
  display_name: Explicit LaTeX Typesetting
  description: |-
    Instead of typesetting LaTeX anywhere, only typeset LaTeX where
    it is explicitly enabled.
  applies_to: SiteAdmin

rce_show_studio_media_options:
  state: hidden
  display_name: Studio Media Options in RCE
  description: |-
   Allow users to resize Canvas Studio embedded media in the RCE via
   a new Studio Media Options tray
  applies_to: SiteAdmin

rce_improved_placeholders:
  state: hidden
  display_name: Use improved placeholders for inserted content in the RCE.
  description: Use new and better styled placeholders for inserted images, videos, and files in the RCE.
  applies_to: SiteAdmin
  environments:
    development:
      state: allowed_on
    beta:
      state: allowed_on
    ci:
      state: allowed_on

rce_transform_loaded_content:
  state: hidden
  display_name: Transform RCE Content on Load
  description: |-
    Transforms absolute URLs to relative URLs and removes extraneous attributes from RCE content on load.
    Needed for the RCE to function fully in New Quizzes.
  applies_to: RootAccount
  environments:
    development:
      state: allowed_on
    beta:
      state: allowed_on
    ci:
      state: allowed_on

media_links_use_attachment_id:
  state: hidden
  display_name: Use Attachment IDs in Media Links
  description: |-
    Use attachment ids in media links so that users are always pointed to the correct instance of media 
    instead of the original
  applies_to: SiteAdmin