---
buttons_and_icons_root_account:
  state: allowed
  applies_to: RootAccount
  display_name: RCE Icon Maker
  description: |-
    Manage a library of custom icons from the RCE.
  environments:
    production:
      state: hidden

buttons_and_icons_cropper:
  state: hidden
  display_name: Cropper & Associated Features in Buttons & Icons
  description: |-
    When enabled, turns on the Button & Icons image cropper, course images
    source, and upload image source.
  applies_to: SiteAdmin

rce_ux_improvements:
  state: hidden
  display_name: RCE UX Improvements
  description: Improve and streamline the RCE button and tray UX
  applies_to: SiteAdmin

rce_better_paste:
  state: hidden
  display_name: Enhanced RCE paste from clipboard
  description: Handle pasting of files, especially images.
  applies_to: SiteAdmin
  environments:
    development:
      state: allowed_on
    beta:
      state: allowed_on
    ci:
      state: allowed_on

explicit_latex_typesetting:
  state: hidden
  display_name: Explicit LaTeX Typesetting
  description: |-
    Instead of typesetting LaTeX anywhere, only typeset LaTeX where
    it is explicitly enabled.
  applies_to: SiteAdmin
