---
check_submission_file_type:
  state: hidden
  applies_to: RootAccount
  display_name: Check Submission File Type
  description: |-
    This feature makes the submissions file upload api check the filetype against
    the allowed extensions of the associated assignment.
caps_site_admin_test_feature:
  state: allowed
  applies_to: SiteAdmin
  display_name: This is a SiteAdmin test Feature Flag
  description: |-
    This flag will not cause any change in behavior.
assignments_2_teacher:
  state: hidden
  display_name: Assignments 2 Teacher View
  description: Use the new assignments teacher page
  applies_to: Course
  root_opt_in: true
  beta: false
  environments:
    production:
      state: disabled
