rce_auto_save:
  state: hidden
  display_name: RCE Auto-Save
  description: |-
    If RCE Enhancements are also enabled,
    the RCE will auto-save your work as you go
  applies_to: Course
  root_opt_in: true
