---
assignments_2_student:
  state: hidden
  display_name: Assignment Enhancements - Student
  description:
    wrapper: <a href="https://community.canvaslms.com/t5/Assignment-Enhancements-Users/gh-p/student_enhancements">\1</a>
    assignments_2_student_description: This feature enhances the assignment submission and feedback workflow for students. When this flag is enabled, early access to ongoing improvements will be displayed automatically with every release. For full details, please see the *Assignment Enhancements User Group* in the Canvas Community.
  applies_to: Course
  root_opt_in: true
  beta: true
assignments_2_teacher:
  state: hidden
  display_name: Assignments 2 Teacher View
  description: Use the new assignments teacher page
  applies_to: Course
  root_opt_in: true
  environments:
    production:
      state: disabled
auto_show_cc:
  type: setting
  state: allowed
  display_name: Auto Show Closed Captions
  description: |-
    Automatically show closed captions in the user's current
    language (if available) when playing canvas media.
  applies_to: User
course_paces:
  state: hidden
  display_name: 'Course Pacing'
  description:
    wrapper: <a href="https://community.canvaslms.com/t5/Course-Pacing-Feature-Preview/gh-p/course_pacing">\1</a>
    course_paces_description: |-
      Course Pacing adds support for rolling enrollments to Canvas;
      allowing magical distribution of due dates for students with different
      start dates based on an instructor's defined pace. Learn more and give
      feedback by joining the *Course Pacing User Group*.
  applies_to: Account
  beta: true
  environments:
    development:
      state: allowed_on
    beta:
      state: allowed_on
    ci:
      state: allowed_on
course_paces_for_sections:
  state: hidden
  display_name: 'Per Section Course Paces'
  description: Enable unique course paces for course sections.
  applies_to: SiteAdmin
  environments:
    development:
      state: allowed_on
    beta:
      state: allowed_on
    ci:
      state: allowed_on
    production:
      state: allowed_on
create_course_subaccount_picker:
  state: hidden
  applies_to: RootAccount
  display_name: 'Allow sub-account selection when users manually create courses'
  description: |-
    Rather than automatically placing manually created courses into the
    "Manually Created Courses" sub-account, when enabled, this feature allows
    people who can manually create courses to put those courses into any sub-account
    where they have enrollments.
conferencing_in_planner:
  state: hidden
  applies_to: SiteAdmin
  display_name: Conferencing in planner
  description: |-
    When enabled, this flag shows a "Join" button on Canvas calendar
    events in the student planner
submission_feedback_indicators:
  state: allowed
  applies_to: RootAccount
  display_name: Submission feedback indicators
  description: |-
    Adds visual indicators to the submission details page to tell students that unread
    document annotations or rubric comments exist
word_count_in_speed_grader:
  state: hidden
  applies_to: RootAccount
  display_name: 'Add word count to SpeedGrader'
  description: |-
    When enabled, this flag displays a word count in the speed grader for text
    based submissions.
  development:
    state: allowed_on
  ci:
    state: allowed_on
observer_picker:
  applies_to: SiteAdmin
  state: hidden
  display_name: Filter observer dashboard by student
  description: |-
    When enabled, this flag shows a student picker for observers on the dashboard.
  environments:
    ci:
      state: allowed_on
    development:
      state: allowed_on
calendar_series:
  applies_to: SiteAdmin
  state: hidden
  display_name: Calendar Series
  description: |-
    This flag allows calendar event series to be created from the Canvas Calendar.
section_level_calendar_permissions:
  applies_to: SiteAdmin
  state: allowed_on
  display_name: Section-level calendar permissions
  description: |-
    Allow permissions to manage the calendar to be granted at a section-level.
account_level_blackout_dates:
  applies_to: SiteAdmin
  state: hidden
  display_name: Account-level course pacing blackout dates
  description: |-
    Allow course pacing blackout dates to be set for accounts instead of just courses.
