---
assignments_2_student:
  state: hidden
  display_name: Assignments 2 Student View
  description: Use the new assignments student page
  applies_to: Course
  root_opt_in: true
  beta: true
  environments:
    production:
      state: disabled

account_pronouns:
  state: hidden
  display_name: Pronouns for users
  description: Allows users to pick pronouns that will be displayed after their name when it is shown in the user interface.
  applies_to: RootAccount
  root_opt_in: true
